import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "../packages/design-system/src/components";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        manrope.variable,
      )}
    >
      <body className="min-h-full w-full flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer
          className="bg-gray-100"
          copyText="© 2026 Marketplace Project. Built for scale."
          logo={
            <div className="text-xl font-black tracking-tighter text-brand-main">
              MARKETPLACE
            </div>
          }
          sections={[
            {
              links: [
                {
                  href: "#",
                  label: "All Categories",
                },
                {
                  href: "#",
                  label: "Featured Stores",
                },
                {
                  href: "#",
                  label: "Sell on Marketplace",
                },
              ],
              title: "Marketplace",
            },
            {
              links: [
                {
                  href: "#",
                  label: "My Profile",
                },
                {
                  href: "#",
                  label: "Order History",
                },
                {
                  href: "#",
                  label: "Settings",
                },
              ],
              title: "Account",
            },
            {
              links: [
                {
                  href: "#",
                  label: "Help Center",
                },
                {
                  href: "#",
                  label: "Community",
                },
                {
                  href: "#",
                  label: "Contact Us",
                },
              ],
              title: "Support",
            },
          ]}
          variant="default"
        />
      </body>
    </html>
  );
}
